# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 202c5592625e1bec4b78e0dd1c1bdd2c99d7698e1f71731ac9723163c2d44b04a256980ea6d6bf6777cceacf46dd668910099ba436f946516e55bfa880ebb08d

test:
  secret_key_base: 7002e09a2c29b563eea753cc8db26064e1c129337bbcbb0166378298ec08ab53f06db74863c2c6e8e1699a172adaf113c25eae1d8962989fe8516ad9da3d1a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
